### ISSUE TITLE
Archive name 'data' was not found in archive name list

### ISSUE THREAD

**Issue by tirohia** [microsoft/BioGPT#119]
Attempting to run the first example in the Getting started section. 

Running on an Ubuntu machine using a fresh conda environment. Python 3.10 and PyTorch1.12.0 installed fine. 
No errors with the installation of moses, fastbpe, sacremoses and scikit-learn. 
 
Placing the code in the first example in the file biogptTest.py and running it, gives this:
```
$ python3 biogptTest.py                                                                                                                                               
2024-01-11 19:27:06 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX                                                                                                              
2024-01-11 19:27:07 | INFO | fairseq.file_utils | Archive name 'checkpoints/Pre-trained-BioGPT' was not found in archive name list. We assumed 'checkpoints/Pre-trained-BioGPT' was a path or URL but couldn't find any file associated to this path or URL.
2024-01-11 19:27:07 | INFO | fairseq.file_utils | Archive name 'data' was not found in archive name list. We assumed 'data' was a path or URL but couldn't find any file associated to this path or URL.
Traceback (most recent call last):
  File "/data/projects/biogpt/src/biogptTest.py", line 3, in <module>
    m = TransformerLanguageModel.from_pretrained(
  File "/data/projects/classifiers/bin/envs/biogpt/lib/python3.10/site-packages/fairseq/models/fairseq_model.py", line 267, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/data/projects/classifiers/bin/envs/biogpt/lib/python3.10/site-packages/fairseq/hub_utils.py", line 66, in from_pretrained
    path = os.path.join(model_path, file)
  File "/data/projects/classifiers/bin/envs/biogpt/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Issues #6 and #14 refer to something similar. 
Issue #6, whilst generating a type error is a different one, and the solution of running with python3 doesn't work here. 
Issue #14 on the other hand, while also not able to find the archive ''data', has a different error trace. Apparently the fix for that was to run all steps in the repo, which I have done, to no avail. 

I've gone into the fairseq repo and checked the branch version is still v 0.12.0
the environment variables for MOSES and FASTBPE are set.
```
(biogpt)$ echo $MOSES
/data/projects/biogpt/bin/mosesdecoder
(biogpt)$ echo $FASTBPE
/data/projects/biogpt/bin/fastbpe
```

I'm looking in the file python3.10/site-packages/fairseq/models/fairseq_model.py, given that this appears to be where this starts. In the comments, it says that the data_name_or_path points to the archive at the given path/url. I am assuming that the first argument is meant to point to the directory that the checkpoint file is in, the second is the name of the checkpoint file, and the third parameter is meant to point so some data structure within the checkpoint file? I can't find any explanation of how this is meant to work. 

Thanks
Ben.

**Comment by tirohia** [comment]
\<le sigh\> 
running from a different location, i.e. the data directory wasn't present.
