### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by him1532** [microsoft/BioGPT#25]
Following the install instruction and following error occurred. How can I resolve this?
Thank you

```
$ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "/home/miniconda3/envs/biogpt/lib/python3.10/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/miniconda3/envs/biogpt/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/miniconda3/envs/biogpt/lib/python3.10/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fairseq/setup.py", line 87, in <module>
    from torch.utils import cpp_extension
  File "/home/miniconda3/envs/biogpt/lib/python3.10/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/miniconda3/envs/biogpt/lib/python3.10/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/home/miniconda3/envs/biogpt/lib/python3.10/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/home/miniconda3/envs/biogpt/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/miniconda3/envs/biogpt/lib/python3.10/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```

**Comment by yuta519** [comment]
I don't have the same problem, but the below looks to help you.

https://stackoverflow.com/questions/74394695/how-does-one-fix-when-torch-cant-find-cuda-error-version-libcublaslt-so-11-no
