### ISSUE TITLE
first example fails

### ISSUE THREAD

**Issue by trigaten** [microsoft/BioGPT#6]
Why might this be happening?

Redhat, torch 1.12.1+cu102, Python 3.9.12

MRE:
```
import torch
from fairseq.models.transformer_lm import TransformerLanguageModel
m = TransformerLanguageModel.from_pretrained(
        "checkpoints/Pre-trained-BioGPT", 
        "checkpoint.pt", 
        "data",
        tokenizer='moses', 
        bpe='fastbpe', 
        bpe_codes="data/bpecodes",
        min_len=100,
        max_len_b=1024)
```
yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/models/fairseq_model.py", line 267, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/hub_utils.py", line 73, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/checkpoint_utils.py", line 378, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/tasks/language_modeling.py", line 180, in build_model
    model = super().build_model(args)
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/tasks/fairseq_task.py", line 633, in build_model
    model = models.build_model(args, self)
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/models/transformer_lm.py", line 264, in build_model
    embed_tokens = cls.build_embedding(
  File "/fs/clip-scratch/sschulho/fairseq/fairseq/models/transformer_lm.py", line 285, in build_embedding
    embed_tokens = Embedding(len(dictionary), embed_dim, dictionary.pad())
TypeError: object of type 'NoneType' has no len()
```

**Comment by trigaten** [comment]
Running with `python3` seems to resolve this.

**Comment by aeolianine** [comment]
I have the same issue, reproduced on two different linux machines, running with python3. (3.10). Any tips?

**Comment by aeolianine** [comment]
Turns out this error was caused by [issue 14](https://github.com/microsoft/BioGPT/issues/14).
