### ISSUE TITLE
Cannot run example code

### ISSUE THREAD

**Issue by btrude** [microsoft/BioGPT#8]
Hello, I am trying to evaluate the models provided here but the dependency installation instructions are slightly unclear. After running through them in the way that I assume you meant (in which I am cloning fairseq and moses into the BioGPT directory, not just naively following the instructions and cloning moses into the fairseq directory as is implied by the lack of `cd` in the instructions), I get the following error: 

```
Traceback (most recent call last):
  File "/opt/workspace/BioGPT/test.py", line 2, in <module>
    from fairseq.models.transformer_lm import TransformerLanguageModel
  File "/usr/local/lib/python3.9/site-packages/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/usr/local/lib/python3.9/site-packages/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 6, in <module>
    from examples.simultaneous_translation.utils.latency import LatencyTraining
ModuleNotFoundError: No module named 'examples.simultaneous_translation'
```

I would be happy to contribute better instructions and resolve the dependencies if someone can provide me the ouput of `pip freeze` from an environment that they know can successfully run the examples provided in the readme of this directory, otherwise any advice is greatly appreciated. Thanks!

**Comment by btrude** [comment]
A normal `pip install fairseq` or running any given script from within the fairseq directory seems to resolve the issue above, however both result in another error:

```
Traceback (most recent call last):
  File "/opt/workspace/BioGPT/fairseq/test.py", line 7, in <module>
    m = TransformerLanguageModel.from_pretrained(
  File "/opt/workspace/BioGPT/fairseq/fairseq/models/fairseq_model.py", line 267, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/opt/workspace/BioGPT/fairseq/fairseq/hub_utils.py", line 73, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/opt/workspace/BioGPT/fairseq/fairseq/checkpoint_utils.py", line 372, in load_model_ensemble_and_task
    task = tasks.setup_task(cfg.task)
  File "/opt/workspace/BioGPT/fairseq/fairseq/tasks/__init__.py", line 42, in setup_task
    assert task is not None, f"Could not infer task type from {cfg}. Available tasks: {TASK_REGISTRY.keys()}"
AssertionError: Could not infer task type from {'_name': 'language_modeling_prompt', 'data': None, 'sample_break_mode': 'none', 'tokens_per_sample': 1024, 'output_dictionary_size': -1, 'self_target': False, 'future_target': False, 'past_target': False, 'add_bos_token': False, 'max_target_positions': 1024, 'shorten_method': 'none', 'shorten_data_split_list': '', 'pad_to_fixed_length': False, 'pad_to_fixed_bsz': False, 'seed': 1, 'batch_size': None, 'batch_size_valid': None, 'dataset_impl': None, 'data_buffer_size': 10, 'tpu': False, 'use_plasma_view': False, 'plasma_path': '/tmp/plasma', 'source_lang': None, 'target_lang': None, 'max_source_positions': 980, 'manual_prompt': None, 'learned_prompt': 9, 'learned_prompt_pattern': 'learned', 'prefix': False, 'sep_token': '<seqsep>'}. Available tasks: dict_keys(['translation', 'multilingual_translation', 'translation_lev', 'language_modeling', 'sentence_ranking', 'sentence_prediction', 'cross_lingual_lm', 'multilingual_masked_lm', 'speech_to_text', 'translation_multi_simple_epoch', 'translation_from_pretrained_bart', 'denoising', 'multilingual_denoising', 'masked_lm', 'translation_from_pretrained_xlm', 'semisupervised_translation', 'audio_pretraining', 'legacy_masked_lm', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt'])
```

**Comment by renqianluo** [comment]
We have updated the dependencies, please see the README.md

**Comment by btrude** [comment]
> This might be due to some dependencies. We have updated the dependencies. Please see the [README.md](https://github.com/microsoft/BioGPT/blob/main/README.md)

Thank you! I will try again as soon as I can :)
